# Generated by Django 2.1 on 2018-09-27 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180926_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_tour',
            name='account',
        ),
        migrations.RemoveField(
            model_name='restaurant_tour',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 345577)),
        ),
        migrations.DeleteModel(
            name='Restaurant_tour',
        ),
    ]
