# Generated by Django 2.1 on 2018-11-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20181116_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, choices=[('Đà Nẵng', 'Đà Nẵng'), ('Hà Nội', 'Hà Nội'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('Đà Lạt', 'Đà Lạt'), ('Nha Trang', 'Nha Trang'), ('Quảng Nam', 'Quảng Nam'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Huế', 'Huế'), ('Gia Lai', 'Gia Lai'), ('Ninh Bình', 'Ninh Bình'), ('Quy Nhơn', 'Quy Nhơn')], default='Đà Nẵng', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 49, 23, 859630)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type_restaurant',
            field=models.CharField(choices=[('Hải Sản', 'Hải Sản'), ('Vỉa Hè', 'Vỉa Hè'), ('Nhậu Bình Dân', 'Nhậu Bình Dân'), ('Nhà Hàng', 'Nhà Hàng'), ('Nướng', 'Nướng')], default='Hải Sản', max_length=250),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
