# Generated by Django 2.1 on 2018-11-23 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_auto_20181123_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 30, 55, 435626)),
        ),
    ]
