# Generated by Django 2.1 on 2018-11-24 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0045_auto_20181124_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 10, 34, 14, 655086)),
        ),
    ]
