# Generated by Django 2.1 on 2018-12-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0055_auto_20181208_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 16, 24, 58, 781321)),
        ),
    ]
