# Generated by Django 2.1 on 2018-12-09 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0056_auto_20181208_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 9, 55, 15, 490877)),
        ),
    ]
