# Generated by Django 2.1 on 2018-12-09 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0057_auto_20181209_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 10, 25, 27, 605404)),
        ),
    ]
