# Generated by Django 2.1 on 2018-09-24 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourer', '0007_remove_tourer_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnet', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 24, 15, 43, 7, 37070))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=250)),
                ('type_place', models.CharField(max_length=250)),
                ('image_place', models.FileField(default='/default/user-avatar-default-165.png', upload_to='place/')),
                ('review', models.IntegerField(default=0)),
                ('star', models.FloatField(default=0)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Place_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_status', models.CharField(max_length=5000)),
                ('end_status', models.CharField(max_length=5000)),
                ('img_status', models.FileField(default='/default/user-avatar-default-165.png', upload_to='place/book/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Place_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 24, 15, 43, 7, 37070))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='comment_place',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
