# Generated by Django 2.1 on 2018-09-25 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_place',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 8, 54, 50, 189645)),
        ),
        migrations.AlterField(
            model_name='place_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 8, 54, 50, 189645)),
        ),
    ]
