# Generated by Django 2.1 on 2018-09-26 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180925_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_place',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 19, 55, 57, 16459)),
        ),
        migrations.AlterField(
            model_name='place_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 19, 55, 57, 16459)),
        ),
    ]
