# Generated by Django 2.1 on 2018-10-09 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20181009_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_place',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 22, 18, 15, 126339)),
        ),
    ]
