# Generated by Django 2.1 on 2018-11-23 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0014_auto_20181116_1710'),
        ('places', '0020_auto_20181116_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 54, 13, 12108))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Place_details',
            new_name='PlaceDetails',
        ),
        migrations.RemoveField(
            model_name='comment_place',
            name='account',
        ),
        migrations.RemoveField(
            model_name='comment_place',
            name='place',
        ),
        migrations.AlterField(
            model_name='place',
            name='type_place',
            field=models.CharField(choices=[('Cầu', 'Cầu'), ('Sông', 'Sông'), ('Hồ', 'Hồ'), ('Núi', 'Núi'), ('Biển', 'Biển')], default='Núi', max_length=250),
        ),
        migrations.DeleteModel(
            name='Comment_place',
        ),
        migrations.AddField(
            model_name='commentplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
