# Generated by Django 2.1 on 2018-11-24 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20181124_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentplace',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 10, 0, 28, 204675)),
        ),
    ]
