# Generated by Django 2.1 on 2018-12-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0032_auto_20181207_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentplace',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 6, 17, 47, 187778)),
        ),
    ]
