# Generated by Django 2.1.4 on 2018-12-26 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0040_auto_20181226_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content1',
            field=models.CharField(default=2016, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentplace',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 6, 9, 58, 874735)),
        ),
    ]
