# Generated by Django 2.1.4 on 2018-12-26 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0042_auto_20181226_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentplace',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 6, 12, 13, 22058)),
        ),
    ]
