# Generated by Django 2.1.4 on 2018-12-26 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0046_auto_20181226_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=models.CharField(default=2016, max_length=1250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentplace',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 9, 25, 45, 379953)),
        ),
    ]
