# Generated by Django 2.1 on 2018-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=250)),
                ('person', models.IntegerField(default=1)),
                ('image_tour', models.FileField(default='/default/user-avatar-default-165.png', upload_to='tour/')),
                ('date_tour', models.FloatField(default=1)),
                ('type_tour', models.CharField(max_length=250)),
            ],
        ),
    ]
