# Generated by Django 2.1 on 2018-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type_tour',
            field=models.CharField(blank=True, choices=[('Du Lịch Trong Nước', 'Du Lịch   Trong Nước'), ('Tour Nước Ngoài', 'Tour Nước Ngoài')], default='Du Lịch Trong Nước', max_length=250, null=True),
        ),
    ]
