# Generated by Django 2.1 on 2018-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20181122_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='person',
            field=models.FloatField(default=1),
        ),
    ]
