# Generated by Django 2.1 on 2018-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20181123_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
