# Generated by Django 2.1 on 2018-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(default=2016, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_tour',
            field=models.CharField(blank=True, choices=[('Du Lịch Trong Nước', 'Du Lịch   Trong Nước'), ('Tour Nước Ngoài', 'Tour Nước Ngoài'), ('unknown', (('abc', 'abc'), ('dvc', 'dvc')))], default='Du Lịch Trong Nước', max_length=250, null=True),
        ),
    ]
