# Generated by Django 2.1 on 2018-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20181124_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, choices=[('Miền Bắc', (('Hà Nội', 'Hà Nội'), ('Sapa', 'Sapa'))), ('Miền Trung', (('Đà Nẵng', 'Đà Nẵng'), ('Quảng Nam', 'Quảng Nam'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quy Nhơn', 'Quy Nhơn'), ('Nha Trang', 'Nha Trang'))), ('Miền Nam', (('Sài Gòn', 'Sài Gòn'), ('Sài Gòn', 'Sài Gòn')))], default='Đà Nẵng', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_tour',
            field=models.CharField(blank=True, choices=[('Du Lịch Trong Nước', 'Du Lịch   Trong Nước'), ('Tour Nước Ngoài', 'Tour Nước Ngoài')], default='Du Lịch Trong Nước', max_length=250, null=True),
        ),
    ]
