# Generated by Django 2.1 on 2018-11-24 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0014_auto_20181116_1710'),
        ('tour', '0008_auto_20181124_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_book', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 10, 40, 52, 93209))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 10, 40, 52, 93209))),
                ('accout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Tourer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Tour')),
            ],
        ),
    ]
