# Generated by Django 2.1 on 2018-11-27 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_booktour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktour',
            options={'ordering': ['date_start']},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AlterField(
            model_name='booktour',
            name='date_book',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 17, 7, 836672)),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 17, 7, 836672)),
        ),
    ]
