# Generated by Django 2.1 on 2018-12-07 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20181207_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktour',
            name='date_book',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 19, 37, 33, 470025)),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 19, 37, 33, 470025)),
        ),
    ]
