# Generated by Django 2.1 on 2018-12-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_auto_20181207_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktour',
            name='date_book',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='date_start',
            field=models.DateField(),
        ),
    ]
