# Generated by Django 2.1 on 2018-12-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20181207_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktour',
            name='accout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourer.Account'),
        ),
    ]
