# Generated by Django 2.1 on 2018-12-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_auto_20181207_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='booktour',
            name='person_book',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='booktour',
            name='phone',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
