# Generated by Django 2.1 on 2018-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_auto_20181208_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktour',
            name='email',
            field=models.CharField(default=2016, max_length=250),
            preserve_default=False,
        ),
    ]
