# Generated by Django 2.1 on 2018-12-09 00:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_booktour_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetour',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
