# Generated by Django 2.1 on 2018-12-09 01:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_auto_20181209_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetour',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
