# Generated by Django 2.1 on 2018-12-10 00:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20181209_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_house', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Tour')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='placetour',
            name='image_place',
        ),
    ]
