# Generated by Django 2.1 on 2018-12-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_auto_20181210_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, choices=[('Miền Bắc', (('Hà Nội', 'Hà Nội'), ('Sapa', 'Sapa'))), ('Miền Trung', (('Đà Nẵng', 'Đà Nẵng'), ('Quảng Nam', 'Quảng Nam'), ('Huế', 'Huế'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quy Nhơn', 'Quy Nhơn'), ('Phú Yên', 'Phú Yên'), ('Nha Trang', 'Nha Trang'), ('Đà Lạt', 'Đà Lạt'))), ('Miền Nam', (('Sài Gòn', 'Sài Gòn'), ('Miền Tây', 'Miền Tây'))), ('Nước ngoài', (('Châu Âu', 'Châu Âu'), ('Châu Á', 'Châu Á'), ('Châu Mĩ', 'Châu Mĩ')))], default='Đà Nẵng', max_length=250, null=True),
        ),
    ]
