# Generated by Django 2.1 on 2018-09-19 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourser',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('avatar', models.FileField(upload_to='tourer/')),
                ('password', models.CharField(max_length=250)),
                ('question', models.CharField(default='question', max_length=250)),
                ('time_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
