# Generated by Django 2.1 on 2018-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourser',
            name='avatar',
            field=models.FileField(default='/media/tourer/WIN_20180830_22_34_34_Pro.jpg', upload_to='tourer/'),
        ),
    ]
