# Generated by Django 2.1 on 2018-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0003_auto_20180919_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourser',
            name='avatar',
            field=models.FileField(default='/tourer/user-avatar-default-165.png', upload_to='tourer/'),
        ),
    ]
