# Generated by Django 2.1 on 2018-09-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0006_auto_20180919_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourer',
            name='time_create',
        ),
    ]
