# Generated by Django 2.1 on 2018-10-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0010_auto_20181009_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourer',
            name='id',
        ),
        migrations.AlterField(
            model_name='tourer',
            name='email',
            field=models.CharField(blank=True, default=2008, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
