# Generated by Django 2.1 on 2018-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0012_auto_20181116_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourer',
            name='id',
        ),
        migrations.AlterField(
            model_name='tourer',
            name='email',
            field=models.CharField(blank=True, max_length=250, primary_key=True, serialize=False),
        ),
    ]
