# Generated by Django 2.1 on 2018-11-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0013_auto_20181116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourer',
            name='author',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('account', 'account')], default='account', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tourer',
            name='avatar',
            field=models.FileField(default='/default/avatar.jpg', upload_to='tourer/'),
        ),
    ]
