# Generated by Django 2.1 on 2018-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0014_auto_20181116_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('avatar', models.FileField(default='/default/avatar.jpg', upload_to='tourer/')),
                ('password', models.CharField(max_length=250)),
                ('question', models.CharField(default='question', max_length=250)),
                ('author', models.CharField(blank=True, choices=[('admin', 'admin'), ('account', 'account')], default='account', max_length=250, null=True)),
            ],
        ),
    ]
