# Generated by Django 2.1 on 2018-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='Funny', max_length=250),
        ),
    ]
