# Generated by Django 2.1 on 2018-12-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourer', '0016_account_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
    ]
