# Generated by Django 2.1 on 2018-09-27 12:34

import book.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourer', '0007_remove_tourer_time_create'),
        ('restaurants', '0004_auto_20180927_1934'),
        ('house', '0011_auto_20180927_1934'),
        ('places', '0005_auto_20180927_1934'),
    ]

    
