# Generated by Django 2.1 on 2018-10-10 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_speak', models.CharField(max_length=250)),
                ('type_speak', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 10, 11, 48, 18, 702492))),
                ('theme', models.FileField(default='/default/user-avatar-default-165.png', upload_to='learn/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSpeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 10, 11, 48, 18, 703491))),
                ('speak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Speak')),
            ],
        ),
    ]
