# Generated by Django 2.1 on 2018-09-20 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 19, 59, 37, 600547)),
        ),
        migrations.AlterField(
            model_name='house_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 19, 59, 37, 601045)),
        ),
    ]
