# Generated by Django 2.1 on 2018-09-20 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180920_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 20, 2, 10, 340993)),
        ),
        migrations.AlterField(
            model_name='house_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 20, 2, 10, 341492)),
        ),
    ]
