# Generated by Django 2.1 on 2018-09-20 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20180920_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='city',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 20, 3, 15, 282441)),
        ),
        migrations.AlterField(
            model_name='house_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 20, 3, 15, 283439)),
        ),
    ]
