# Generated by Django 2.1 on 2018-09-20 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20180920_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='room_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 22, 58, 46, 282483)),
        ),
        migrations.AlterField(
            model_name='house_tour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 22, 58, 46, 282981)),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
