# Generated by Django 2.1 on 2018-09-27 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20180926_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_tour',
            name='account',
        ),
        migrations.RemoveField(
            model_name='house_tour',
            name='house',
        ),
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 19, 34, 50, 336582)),
        ),
        migrations.DeleteModel(
            name='House_tour',
        ),
    ]
