# Generated by Django 2.1 on 2018-10-09 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_auto_20181009_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 22, 21, 40, 381934)),
        ),
    ]
