# Generated by Django 2.1 on 2018-11-16 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_auto_20181010_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 46, 58, 586603)),
        ),
    ]
