# Generated by Django 2.1 on 2018-11-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0022_auto_20181116_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 16, 49, 23, 851634)),
        ),
    ]
