# Generated by Django 2.1 on 2018-11-22 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0027_auto_20181122_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 16, 29, 48, 807334)),
        ),
    ]
