# Generated by Django 2.1 on 2018-11-22 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0028_auto_20181122_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 17, 30, 33, 449437)),
        ),
    ]
