# Generated by Django 2.1 on 2018-11-23 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0034_auto_20181123_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_house',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='comment_house',
            old_name='commnet',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 14, 52, 250280)),
        ),
    ]
