# Generated by Django 2.1 on 2018-11-23 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0037_auto_20181123_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 26, 40, 43900)),
        ),
    ]
