# Generated by Django 2.1 on 2018-11-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0046_auto_20181123_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 52, 49, 268429)),
        ),
    ]
