# Generated by Django 2.1 on 2018-11-27 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0054_auto_20181124_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 17, 7, 735650)),
        ),
    ]
